# Generated by Django 3.2.12 on 2022-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_status_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.AddField(
            model_name='board',
            name='meta',
            field=models.JSONField(blank=True, help_text='Additional data for the board', null=True, verbose_name='Meta'),
        ),
    ]
