# Generated by Django 3.2.12 on 2022-04-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220424_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_complete_status',
            field=models.BooleanField(default=False),
        ),
    ]
