# Generated by Django 3.2.12 on 2022-04-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_status_is_complete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.JSONField(blank=True, help_text='task order data', null=True, verbose_name='Tasks Order'),
        ),
    ]
